ruby '>=3.0'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.4'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.6.0'
gem 'nokogiri', '~> 1.13.3'
# gem 'mini_racer', '~> 0.6.2'
gem 'translit', '~> 0.1.5'
# gem 'haml', '~> 5.0'
gem 'sass'
gem 'webrick'
